### ISSUE TITLE
TRAVIS CI error en método division(miw.FractionTest)

### ISSUE THREAD

**Issue by albertobricio** [albertobricio/IWVG.SwC.AlbertoBricio#5]
Hola chicos, al parecer en Travis salta un error en los test de la clase fraction en el método division. Si alguien puede solucionarlo. Que cree una rama y fusione los cambios con develop. Un saludo.

**Comment by jotaseme** [comment]
Arreglado. El método devolvía un entero en lugar de un double y era necesario hacer un casting.

Si hay algun problema, avísame.
Saludos!

**Comment by jotaseme** [comment]
He visto que ha pasado los test de travis asique cierro.

Saludos!
